import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {products,filterProducts,formatBRL} from '../src/data/catalog.js';
const url=process.env.QA_URL||'http://127.0.0.1:4174';const out='qa-artifacts/template';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
try{for(const [width,height] of [[1440,900],[1920,1080],[768,1024],[390,844],[375,812]])for(const theme of ['light','dark']){
 const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});await context.addInitScript(theme=>{localStorage.setItem('store_theme',theme);localStorage.setItem('store_cookie_consent','rejected')},theme);
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const badRequests=[];page.on('response',r=>{if(r.url().startsWith(url)&&r.status()>=400)badRequests.push(r.url())});
 for(const route of ['/','/loja','/contato','/assistencia']){await page.goto(url+route);await page.locator('main h1').first().waitFor();await page.waitForTimeout(200);assert.equal(await page.locator('html').getAttribute('data-theme'),theme);assert.ok(!/miphone|mi\.phonestore|Augustinópolis|Araguatins|Moto Elétrica/i.test(await page.locator('body').innerText()));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),width+' '+route+' overflow');assert.equal(await page.locator('a[href*="maps"]').count(),0);for(const href of await page.locator('a[href*="wa.me"]').evaluateAll(es=>es.map(e=>e.href)))assert.equal(new URL(href).pathname,'/5563991399775');await page.screenshot({path:path.join(out,width+'-'+theme+'-'+(route.slice(1)||'home')+'.png')});
 if(route==='/'){assert.equal(await page.locator('#produtos .product-card').count(),4);assert.equal(await page.locator('#instagram .ig-tile img').count(),6);for(const text of ['500','50,1 mil','100'])assert.ok((await page.locator('.demo-ig-stats').innerText()).includes(text));await page.locator('#instagram').scrollIntoViewIfNeeded();await page.locator('#instagram').screenshot({path:path.join(out,width+'-'+theme+'-instagram.png')});if(width<1024){await page.getByRole('button',{name:'Abrir menu',exact:true}).click();assert.equal(await page.locator('a[href="/moto-eletrica"]').count(),0);await page.getByRole('button',{name:theme==='dark'?'Modo claro':'Modo escuro',exact:true}).click();assert.equal(await page.locator('html').getAttribute('data-theme'),theme==='dark'?'light':'dark');await page.getByRole('button',{name:theme==='dark'?'Modo escuro':'Modo claro',exact:true}).click();await page.getByRole('button',{name:'Abrir menu',exact:true}).click()}}
 if(route==='/loja'){assert.equal(await page.locator('.product-card').count(),12);await page.getByRole('textbox',{name:'Buscar produtos'}).fill('Samsung');assert.equal(await page.locator('.product-card').count(),0);await page.getByRole('textbox',{name:'Buscar produtos'}).fill('iPhone 13');assert.ok(await page.locator('.product-card').count()>0);await page.getByRole('textbox',{name:'Buscar produtos'}).fill('');await page.getByRole('button',{name:/Ordenar produtos:/}).click();await page.getByRole('option',{name:'Menor preço',exact:true}).click();assert.equal(await page.locator('.product-card-title a').first().innerText(),filterProducts({sort:'menor'})[0].name);await page.getByRole('button',{name:'Alternar para lista',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Alternar para grade',exact:true}).click();await page.getByRole('button',{name:/Filtrar disponibilidade:/}).click();await page.getByRole('option',{name:'Disponíveis',exact:true}).click();assert.equal(await page.locator('.product-card').count(),filterProducts({availability:'disponiveis'}).length)}
 }
 const phone=products.find(p=>p.variants.length);await page.goto(url+'/loja/produto/'+phone.slug);const buy=page.getByRole('button',{name:'Comprar',exact:true});assert.ok(await buy.isDisabled());for(const attr of phone.variants[0].attributes){const group=page.locator('fieldset').filter({has:page.locator('legend', {hasText:attr.name})});await group.getByRole('button').filter({hasText:new RegExp('^'+attr.value.replace(/(\d+)\s*(gb|tb)/ig,'$1 $2')+'$','i')}).click()}
 assert.ok(await buy.isEnabled());await page.getByRole('button',{name:'Adicionar ao carrinho',exact:true}).click();await page.getByRole('button',{name:'Aumentar quantidade do item',exact:true}).click();assert.equal(await page.locator('.cart-panel .cart-qty span').innerText(),'2');const link=page.getByRole('link',{name:'Finalizar pedido',exact:true});const checkout=new URL(await link.getAttribute('href'));assert.equal(checkout.pathname,'/5563991399775');const message=checkout.searchParams.get('text');assert.ok(message.includes('Quantidade: 2'));assert.ok(message.includes('TOTAL DEMONSTRATIVO: '+formatBRL(phone.variants[0].price*2)));assert.ok(message.includes('Cor:'));assert.ok(message.includes('Armazenamento:'));await page.screenshot({path:path.join(out,width+'-'+theme+'-cart.png')});
 // Intercept the outbound request to verify the actual button opens the intended URL without sending a message.
 await context.route('https://wa.me/**',route=>route.fulfill({status:200,contentType:'text/html',body:'<title>WhatsApp checkout verified</title>'}));const popupPromise=page.waitForEvent('popup');await link.click();const popup=await popupPromise;await popup.waitForLoadState();assert.equal(new URL(popup.url()).pathname,'/5563991399775');await popup.close();await page.getByRole('button',{name:'Remover',exact:true}).click();assert.equal(await page.locator('.cart-item').count(),0);await page.getByRole('button',{name:'Fechar carrinho',exact:true}).click();
 const incomplete=products.find(p=>p.variationsIncomplete);await page.goto(url+'/loja/produto/'+incomplete.slug);assert.ok(await page.getByRole('button',{name:'Comprar',exact:true}).isDisabled());await page.goto(url+'/loja/produto/removido');assert.equal(await page.locator('.product-purchase-actions').count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(badRequests,[]);results.push({width,height,theme,passed:true});console.log(width+' '+theme+' passed');await context.close();
 }
 // Real cinema scroll, video decoding, and theme swap.
 const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();await page.goto(url);await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);await page.evaluate(()=>{const v=document.querySelector('video');v.currentTime=Math.min(2,v.duration/2)});await page.waitForTimeout(300);await page.locator('video').screenshot({path:path.join(out,'cinema-frame.png')});await page.evaluate(()=>window.scrollTo(0,1000));await page.waitForTimeout(300);assert.ok(Number(await page.locator('#hero').evaluate(e=>e.style.getPropertyValue('--cine-progress')))>0);await context.close();
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify({passed:true,results,cinema:true},null,2));
}finally{await browser.close()}


