import {createHash} from 'node:crypto'
const imageHashes=["52c0d6b4272a5558f129c2221ed33b67588c1b87657dd02d7575209b7ef81868","33746e47fb58d87e4aaee84df42f4a5fa7f8c1fe4a16620c03222398735be9b7","3b043ba47c373fff16be8fda05fd852cb9aaeb61b884b4165809b53dafec7ff5","f22f7629b40ca42cbede0a02bb38bc89d8d97be28109104a2e763ce92f6a465e","23dea8632d2ab5cd8a1dcba3cedce61a0b025fee698fc49756f5d2a61cb36b21","2417286c0591e9b7d5f6429011dcef3cc1abdae3b70d9bfa63afeca24ccac82d"]
import fs from 'node:fs';import assert from 'node:assert/strict';import path from 'node:path';import {products,filterProducts,makeCartItem,canAddProduct} from '../src/data/catalog.js';import {checkoutUrl} from '../src/config/checkout.js';
const initial=JSON.parse(fs.readFileSync('scripts/fixtures/catalog-baseline.json'));
assert.equal(products.length,12);assert.ok(products.every(p=>/^iphone\b/i.test(p.name)));assert.equal(filterProducts().length,12);
for(const p of products){const old=initial.find(o=>o.id===p.id);for(const key of ['price','regularPrice','salePrice','compareAt','stock','available','purchasable','requiresOptions','variationsIncomplete'])assert.deepEqual(p[key],old[key]);assert.deepEqual(p.variants.map(v=>[v.id,v.price,v.stock,v.attributes]),old.variants.map(v=>[v.id,v.price,v.stock,v.attributes]));for(const m of p.media)for(const url of [m.src,m.thumbnail])assert.ok(fs.existsSync(path.join('public',url)));if(p.variationsIncomplete)assert.equal(canAddProduct(p),false)}
for(const query of ['samsung','xiaomi','capinha','cabo','sandisk','moto'])assert.equal(filterProducts({query}).length,0);
assert.ok(filterProducts({query:'iphone 13 128 gb'}).length>0);
for(const sort of ['menor','maior']){const list=filterProducts({sort});assert.ok(list.every((p,i)=>!i||(sort==='menor'?list[i-1].price<=p.price:list[i-1].price>=p.price)))}
const phone=products.find(p=>p.variants.length);assert.equal(makeCartItem(phone),null);for(const v of phone.variants)assert.ok(makeCartItem(phone,v,2));
assert.equal(makeCartItem({...phone,available:false},phone.variants[0]),null);assert.equal(makeCartItem(initial.find(p=>!/iphone/i.test(p.name))),null);
const items=[makeCartItem(phone,phone.variants[0],2),makeCartItem(products.find(p=>!p.requiresOptions),null,1)];const url=new URL(checkoutUrl(items));assert.equal(url.pathname,'/5563991399775');const message=url.searchParams.get('text');assert.ok(message.includes('PRODUTO 2'));assert.ok(message.includes('Quantidade: 2'));assert.ok(message.includes('Cor:'));assert.ok(message.includes('Armazenamento:'));assert.ok(message.includes('TOTAL DEMONSTRATIVO'));assert.equal(checkoutUrl([]),null);assert.equal(checkoutUrl([{...items[0],productId:'invalid'}]),null);assert.equal(checkoutUrl([{...items[0],quantity:1000}]),null);
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
for(const dir of ['src','public','dist'])for(const p of walk(dir).filter(p=>/\.(js|jsx|json|css|html)$/.test(p)))assert.ok(!/miphone|mi\.phonestore|linktr\.ee|maps\.app\.goo\.gl|google\.com\/maps|moto-eletrica|98489.?6383|99997.?1938/i.test(fs.readFileSync(p,'utf8')),p);
for(let i=1;i<=6;i++){const data=fs.readFileSync('public/instagram/post'+i+'.jpg');assert.equal(createHash('sha256').update(data).digest('hex'),imageHashes[i-1]);}
console.log(JSON.stringify({passed:true,iphones:12,removed:89,variants:6,pricesPreserved:true,guardedIncomplete:4,checkout:true,activeAndBuildAudit:true,providedImagesPreserved:true},null,2));
